[package]
name = "excel2sofia-viewer"
version = "0.3.6"
edition = "2024"
description = "Viewer for excel2sofia output files"
authors = ["Matthias Eberhardt <m.eberhardt@optoneering.com>"]
repository = "https://github.com/matebeulm/excel2sofia-viewer"

[package.metadata.wix]
upgrade-guid = "042F94D0-7281-47FC-A5A7-CB65C4F71171"
path-guid = "B76C2069-3629-4CE7-9DCB-EC7DA95ED488"
license = false
eula = false

[dependencies]
eframe = "0.31"
egui_plot = "0.31"
catppuccin-egui = { version = "5.7.0", default-features = false, features = ["egui31"] }
image = { version = "0.25", default-features = false, features = ["png"] }
rfd = "0.17.2"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
dirs = "6"

[build-dependencies]
winresource = "0.1"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
